export enum RoleEnum {
  ROLE_SYSTEMADMIN = 'SYSTEMADMIN', // SYSTEM...
  ROLE_SUPERADMIN = 'SUPERADMIN', // GET ALL DATA
  ROLE_ADMIN = 'ADMIN', // JUST GET THEIR REGION
  LEADER = 'LEADER', // JUST GET THEIR REGION
  PEMIMPIN_PERSEKUTUAN = 'PEMIMPIN_PERSEKUTUAN', // JUST GET THEIR GROUP
  PEMBIMBING = 'PEMBIMBING', // JUST GET THEIR CHILD
}
